# Generated by Django 2.2.2 on 2019-06-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('f_name', models.TextField()),
                ('l_name', models.TextField()),
                ('phone_num', models.TextField()),
            ],
        ),
    ]
